import type { Metadata } from "next";
import { DocPage, Section, Endpoint } from "../_components/DocPage";

export const metadata: Metadata = { title: "API reference" };
const toc = [{ id: "auth", label: "Authentication" }, { id: "agents", label: "Agents and keys" }, { id: "vaults", label: "Vaults" }, { id: "payments", label: "Payments and activity" }, { id: "health", label: "Health" }];

export default function ReferencePage() {
  return <DocPage eyebrow="Operate" title="API reference" description="A compact route map for the hosted API. Workspace-management routes require operator authority; payment routes require an agent key." toc={toc}>
    <Section id="auth" title="Authentication"><p>Send <code className="font-mono text-text">Authorization: Bearer &lt;credential&gt;</code>. The API accepts active <code className="font-mono text-text">pb_live_…</code> keys and valid Supabase user access tokens. User sessions cannot initiate agent payments.</p></Section>
    <Section id="agents" title="Agents and keys"><div className="space-y-3"><Endpoint method="GET" path="/v1/agents" description="List agents visible to the authenticated principal."/><Endpoint method="POST" path="/v1/agents" description="Provision an offline agent, managed signer, vault record, and one-time agent key. Operator only."/><Endpoint method="GET" path="/v1/api-keys" description="List key metadata without hashes or raw secrets. Operator only."/><Endpoint method="POST" path="/v1/api-keys" description="Issue a new agent or operator key. Operator only."/><Endpoint method="DELETE" path="/v1/api-keys/:id" description="Revoke a workspace key. Operator only."/></div></Section>
    <Section id="vaults" title="Vaults"><div className="space-y-3"><Endpoint method="GET" path="/v1/vaults" description="List workspace vault records."/><Endpoint method="GET" path="/v1/vaults/:id/chain-state" description="Read authoritative state for a live Arc vault."/><Endpoint method="PATCH" path="/v1/vaults/:id" description="Edit offline policy or attach a verified live contract. Live contract rules cannot be changed here."/><Endpoint method="POST" path="/v1/vaults/:id/sync" description="Refresh the workspace mirror from Arc."/><Endpoint method="POST" path="/v1/vaults/:id/fund" description="Verify and record a mined native-USDC funding transfer."/><Endpoint method="POST" path="/v1/signers/rotate/prepare" description="Provision one pending signer for owner-authorized live rotation."/><Endpoint method="POST" path="/v1/signers/rotate/confirm" description="Verify rotation proof and promote the pending signer."/><Endpoint method="POST" path="/v1/signers/pause" description="Pause or resume offline preflight only. Live pause is an owner contract action."/><Endpoint method="POST" path="/v1/signers/revoke" description="Revoke hosted signer access and report required live-vault owner action."/></div></Section>
    <Section id="payments" title="Payments and activity"><div className="space-y-3"><Endpoint method="POST" path="/v1/payments" description="Submit an idempotent payment proposal. Agent key required."/><Endpoint method="GET" path="/v1/payments/:id" description="Read one payment request in the authenticated scope."/><Endpoint method="GET" path="/v1/activity" description="Read workspace activity assembled from payment and indexed chain records."/><Endpoint method="GET" path="/v1/audit/export" description="Export workspace audit data as CSV, or JSON with ?format=json."/></div></Section>
    <Section id="health" title="Health"><div className="space-y-3"><Endpoint method="GET" path="/health" description="Process liveness and non-secret service status."/><Endpoint method="GET" path="/ready" description="Readiness gate; production is ready only when durable persistence is configured and healthy."/></div></Section>
  </DocPage>;
}
